#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          newrelic-plugins
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The New Relic Server Monitoring Plugins
# Description:       The New Relic Server Monitoring Plugins
### END INIT INFO

LANG=
RUN=/var/run/newrelic/newrelic-plugin-agent.pid
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
LABEL=newrelic-plugins
NAME=newrelic-plugins
DESC="New Relic Server Monitoring Plugins"

start() {
    echo -n "Starting $DESC"

    if [ -f $RUN ]; then
        echo "\033[1;31m [ ERROR ] \033[0m - PID file exist: $RUN"
    else 
        /usr/local/bin/newrelic-plugin-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
        echo "\033[1;32m [ OK ] \033[0m"
    fi
}

stop() {
    echo -n "Stopping $DESC"

    if [ ! -f $RUN ]; then
        echo "\033[1;31m [ ERROR ] \033[0m - no PID file detected $RUN"
    else
        PID=`cat $RUN`
        /bin/kill -9 $PID
        rm -f $RUN

        echo "\033[1;32m [ OK ] \033[0m"        
    fi
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    start || exit 1
    ;;
  stop)
    stop || exit 1
    ;;
  restart)
    stop || exit 1
    sleep 1
    start || exit 1
    ;;
  *)
    echo "Usage: /etc/init.d/$LABEL {start|stop|restart}"
    exit 1
    ;;
esac

exit 0